### ISSUE TITLE
Typos is alt text

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/generic-scratch3-high-score#6]
A volunteer noticed a typo and ambiguity in the alt text for this ingredient:

![click **make make** a variable](images/make-variable-annotated.png) - double 'make'

![enter name high score](images/make-high-score-variable.png) - not sure whether 'to' is missing before 'high score' or whether there should be 'the' before 'name'.

**Comment by martinohanlon** [comment]
I have updated the alt text for the images.

```
![variables menu with Make a Variable highlighted](images/make-variable-annotated.png)
![new variable popup box with high score as the variable name](images/make-high-score-variable.png)
```
